name: Reusable Workflow Release

on:
  push:
    branches: [main]

  repository_dispatch:
    types: [semantic-release]

  workflow_dispatch:

permissions: read-all

jobs:
  release:
    permissions:
      actions: write
      contents: write
    uses: mBlomsterberg/hanayama-workflows/.github/workflows/reusable_release.yml@main
    secrets:
      github-token: ${{secrets.PAT}}

  docs:
    needs: [release]
    runs-on: ubuntu-latest
    permissions:
      actions: write 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"